<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'kode_produk' => 'PRD001',
                'nama_produk' => 'Beras Premium 5kg',
                'deskripsi_produk' => 'Beras premium kualitas terbaik, pulen dan wangi',
                'harga_produk' => 75000,
                'diskon_produk' => 5000,
                'stok_produk' => 100,
                'berat_produk' => 5.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Beras+Premium',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD002',
                'nama_produk' => 'Minyak Goreng 2L',
                'deskripsi_produk' => 'Minyak goreng kemasan 2 liter',
                'harga_produk' => 35000,
                'diskon_produk' => 3000,
                'stok_produk' => 150,
                'berat_produk' => 2.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Minyak+Goreng',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD003',
                'nama_produk' => 'Gula Pasir 1kg',
                'deskripsi_produk' => 'Gula pasir murni berkualitas',
                'harga_produk' => 15000,
                'diskon_produk' => 0,
                'stok_produk' => 200,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Gula+Pasir',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD004',
                'nama_produk' => 'Tepung Terigu 1kg',
                'deskripsi_produk' => 'Tepung terigu serbaguna untuk berbagai masakan',
                'harga_produk' => 12000,
                'diskon_produk' => 1000,
                'stok_produk' => 120,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Tepung+Terigu',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD005',
                'nama_produk' => 'Kopi Bubuk 200g',
                'deskripsi_produk' => 'Kopi bubuk premium dengan aroma khas',
                'harga_produk' => 25000,
                'diskon_produk' => 5000,
                'stok_produk' => 80,
                'berat_produk' => 0.2,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Kopi+Bubuk',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD006',
                'nama_produk' => 'Susu UHT 1L',
                'deskripsi_produk' => 'Susu UHT full cream kemasan 1 liter',
                'harga_produk' => 18000,
                'diskon_produk' => 2000,
                'stok_produk' => 100,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Susu+UHT',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD007',
                'nama_produk' => 'Telur Ayam 1kg',
                'deskripsi_produk' => 'Telur ayam segar berkualitas',
                'harga_produk' => 28000,
                'diskon_produk' => 0,
                'stok_produk' => 90,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Telur+Ayam',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD008',
                'nama_produk' => 'Daging Ayam 1kg',
                'deskripsi_produk' => 'Daging ayam segar tanpa tulang',
                'harga_produk' => 45000,
                'diskon_produk' => 5000,
                'stok_produk' => 50,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Daging+Ayam',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD009',
                'nama_produk' => 'Sabun Cuci Piring 800ml',
                'deskripsi_produk' => 'Sabun cuci piring anti bakteri',
                'harga_produk' => 12000,
                'diskon_produk' => 2000,
                'stok_produk' => 150,
                'berat_produk' => 0.8,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Sabun+Cuci',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD010',
                'nama_produk' => 'Detergen 1kg',
                'deskripsi_produk' => 'Detergen bubuk wangi segar',
                'harga_produk' => 18000,
                'diskon_produk' => 0,
                'stok_produk' => 120,
                'berat_produk' => 1.0,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Detergen',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD011',
                'nama_produk' => 'Shampoo 340ml',
                'deskripsi_produk' => 'Shampoo anti ketombe',
                'harga_produk' => 22000,
                'diskon_produk' => 3000,
                'stok_produk' => 80,
                'berat_produk' => 0.34,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Shampoo',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_produk' => 'PRD012',
                'nama_produk' => 'Pasta Gigi 150g',
                'deskripsi_produk' => 'Pasta gigi untuk gigi putih',
                'harga_produk' => 15000,
                'diskon_produk' => 2000,
                'stok_produk' => 100,
                'berat_produk' => 0.15,
                'foto_produk' => 'https://via.placeholder.com/400x400?text=Pasta+Gigi',
                'status_produk' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tb_produk')->insert($products);
    }
}
